version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: des_profectum
      POSTGRES_USER: guinafelix
      POSTGRES_PASSWORD: User2023
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

